# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: book_manager_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: book_manager_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: book_manager_production
  pool: 5
  username: root
  password:
