# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: add415af001e5c00977ce79f343ea00b3574e6fee0344b7ddb09e8a1ca192a000ca80be60682a510c366a3e4c4745aea9de0fb942affe3ccdc6c7abcca21f472

test:
  secret_key_base: 80582650d8020d23042a5608296e9a7ac06bc62659b140b5dfdb4db79c6d6f062ec81155852cb064401e05083584cc33b359e4a1c4681111690fcf929fc28f66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
